plugins {
    id 'application'
//  id 'maven-publish'
    id 'checkstyle'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation libs.guava
    implementation 'org.xerial:sqlite-jdbc:3.45.1.0'
    implementation 'org.slf4j:slf4j-simple:2.0.9'
}
//publishing {
//    repositories {
//        maven {
//            name = "GitHubPackages"
//            url = "https://maven.pkg.github.com/octocat/hello-world"
//            credentials {
//                username = System.getenv("GITHUB_ACTOR")
//                password = System.getenv("GITHUB_TOKEN")
//            }
//        }
//    }
//}
testing {
    suites {
        test {
            useJUnit('4.13.2')
        }
    }
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    mainClass = 'memoir.App'
}
